### ISSUE TITLE
ERROR - create_trees<> failed execute

### ISSUE THREAD

**Issue by zh9118** [sfu-compbio/citup#2]
Hi there,

I have encountered into an error when running testing data. Could anyone kindly help please? Thanks.

Below are the error messages:
`2022-03-28 18:32:36,500 - execqueue - ERROR - create_trees<> failed to complete`
`2022-03-28 18:32:36,501 - scheduler - ERROR - create_trees<> failed execute`
`2022-03-28 18:32:36,501 - scheduler - ERROR - pipeline failed`
`Traceback (most recent call last):`
`   File "./citup_iter.py", line 58, in <module>`
`   pyp.run()`
`  File "~/.conda/envs/py2/lib/python2.7/site-packages/pypeliner/easypypeliner.py", line 140, in run`
`    return self.sch.run(self.exec_queue)`
`  File "~/.conda/envs/py2/lib/python2.7/site-packages/pypeliner/scheduler.py", line 244, in run`
`    raise helpers.PipelineException('pipeline failed')`
`pypeliner.helpers.PipelineException: pipeline failed`

**Comment by smalikic** [comment]
Hi zh9118,
Can you please send me your question via e-mail to salemmalikic05@gmail.com? I have a simpler implementation of CITUP, not released yet, and I would be glad to share it with you and help it run it. 
Thank you.
Salem
