### ISSUE TITLE
Error when I Run any Instructions

### ISSUE THREAD

**Issue by Wesady** [sfu-compbio/citup#3]
HI, I have installed citup and h5py, but I have an error when I run any instructions. Could you please help me?

(citup) icebreaker@ubuntu:~$ run_citup_iter.py -h
Traceback (most recent call last):
  File "/home/icebreaker/anaconda3/envs/citup/bin/run_citup_iter.py", line 4, in <module>
    __import__('pkg_resources').run_script('citup==0.1.0', 'run_citup_iter.py')
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/citup-0.1.0-py2.7.egg/EGG-INFO/scripts/run_citup_iter.py", line 3, in <module>
    __requires__ = 'citup==0.1.0'
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/pypeliner/__init__.py", line 3, in <module>
    import scheduler
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/pypeliner/scheduler.py", line 10, in <module>
    import pypeliner.graph
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/pypeliner/graph.py", line 2, in <module>
    import networkx
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/networkx/__init__.py", line 98, in <module>
    import networkx.utils
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/networkx/utils/__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/networkx/utils/decorators.py", line 14, in <module>
    from decorator import decorator
  File "/home/icebreaker/anaconda3/envs/citup/lib/python2.7/site-packages/decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax

**Comment by smalikic** [comment]
Hi IceBrecker,

Thank you for your interest in CITUP. I have a new implementation of CITUP (implementing the same thing but not released yet), and I expect that it would not have these issues. Can you please reach me by e-mail at: salemmalikic05@gmail.com.

Salem
